name: routiner
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
  date_picker_timeline: ^1.2.7
  equatable: ^2.0.7
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_custom_clippers: ^2.1.0
  flutter_slidable: ^4.0.0
  flutter_snake_navigationbar: ^0.6.1
  font_awesome_flutter: ^10.9.0
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  google_sign_in: ^7.1.1
  lucide_icons: ^0.257.0
  timeago: ^3.7.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/onboarding/
  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCereal_W_Bd.otf
          weight: 700
        - asset: assets/fonts/AirbnbCereal_W_Md.otf
          weight: 500
        - asset: assets/fonts/AirbnbCereal_W_Bk.otf
          weight: 600
        - asset: assets/fonts/AirbnbCereal_W_Blk.otf
          weight: 900
        - asset: assets/fonts/AirbnbCereal_W_Lt.otf
          weight: 300
        - asset: assets/fonts/AirbnbCereal_W_XBd.otf
          weight: 800
